/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wycdqqbpadyswxbzwuxe"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5Y2RxcWJwYWR5c3d4Ynp3dXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNDk0NTQsImV4cCI6MjA4ODcyNTQ1NH0.F2myNVxah1i4oDsXrFTIhuT491fMSjJb9wJd4-K-53c"